services:
  amd64:
    platform: linux/amd64
    build: .
    image: rails-dev-container-example-amd64
    volumes:
      - .:/app
      - node_modules_amd64:/app/node_modules
      - rubygem_bundle_amd64:/usr/local/bundle
      - /app/tmp
      - /app/public/packs
  arm64:
    platform: linux/arm64
    build: .
    image: rails-dev-container-example-arm64
    volumes:
      - .:/app
      - node_modules_amd64:/app/node_modules
      - rubygem_bundle_arm64:/usr/local/bundle
      - /app/tmp
      - /app/public/packs
volumes:
  node_modules_amd64:
  rubygem_bundle_amd64:
  node_modules_arm64:
  rubygem_bundle_arm64:
