services:
  rails:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    platform: linux/amd64
    image: rails_dev_container_example
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
    command: sleep infinity
  webpack:
    image: rails_dev_container_example
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - 3035:3035
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: bin/webpack-dev-server
